server:
  port: 8082
temporal:
  host: localhost:7233
  worker-threads: 10
  max-activities: 200
  max-workflows: 200

dgs:
  graphql:
    schema-locations:
      - classpath*:custom-schema/**/*.graphql*
