{
 "title": "Temporal Stats",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Order workflow", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Order workflow failed / s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(workflow_failed{namespace=\"default\", operation=\"CompletionStats\"}[2m]))"
    }
   ]
  },
  {
   "title": "Order workflow complete / s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(workflow_success{namespace=\"default\", operation=\"CompletionStats\"}[2m]))"
    }
   ]
  },
  {
   "title": "Order workflow starts / s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(service_requests{namespace=\"default\", operation=\"StartWorkflowExecution\"}[2m]))"
    }
   ]
  }
 ]
}